### PR TITLE
#43 - Fixes error messages and safe creation bug fixes

### LINKED ISSUE #43: Catch the insufficient fund error while invoking contract
## Description:
Catch the insufficient fund if the beneficiary doesn't have funds while creating the claim.

## Expected outcome:
Claim error for not having funds while invoking the contract throws a generic error. Respond with a proper contract initiation error.

### LINKED ISSUE #44: Throw an error if the recovery by beneficiary fails
## Description:
Recovery by beneficiary returns `undefined` on `data` field. Return an appropriate error.

### LINKED ISSUE #45: Self safe creation creates safe offchain but not onchain
## Description:
A safe whose beneficiary is self fails onchain but creates a safe onchain. Throw an error without creating a safe offchain.

### PR DESCRIPTION
**Pull request by yathishram**
## Description:
This PR fixes self safe creation, insufficient funds errors by handling them.

## Modified:

List the modified features
* `createSafe` - Adds a check to throw an error when the creator adds himself as beneficiary.
* `recoveryByBeneficary` - Returns an appropriate error when beneficiary tries to recover the safe before any claim or recovery by the guardian.
* `createClaim` - Returns an error if the user funds are less than a predetermined level which is `0.1ETH`

### CODE REVIEW

File: src/SafientCore.ts [hunk 1]
```diff
@@ -497,53 +500,70 @@ export class SafientCore {
...
-        if (safe.claimType === Types.ClaimType.ArbitrationBased) {
-          if (safe.stage === SafeStages.ACTIVE) {
-            evidenceUri = await createClaimEvidenceUri(file, evidenceName, description);
-            tx = await this.contract.createClaim(safe._id, evidenceUri);
-            txReceipt = await tx.wait();
-          }
-        } else if (safe.claimType === Types.ClaimType.SignalBased) {
-          if (safe.stage === SafeStages.ACTIVE) {
+      
+      if(parseInt(etherBalance) >= 0.1){
```
Comment (koshikraj) [inline src/SafientCore.ts:513]: Compare with the safeFee constant

**Review by koshikraj — APPROVED** [review]

**Review by koshikraj — APPROVED** [review]
