### PR TITLE
#37 - Simultaneous safe reconstruction fix and updating user schema

### LINKED ISSUE #36: Add a new field to identify the guardian in `User` data
## Description:
Need a way to distinguish the guardian from normal users.

## Things to do:

- [ ] Add a field `guardian` (`bool`) to check if the user is a guardian
- [ ] Select only the opted guardians for a safe

### LINKED ISSUE #37: Simlutaneous safe reconstruction by guardians doesn't update the stage to `RECOVERED`
## Description:
If 2 or 3 guardians simultaneously reconstruct the safe stage doesn't get updated. One way to fix this is by fetching the safe stage on `getSafe` by checking the number of `decData` updates on `Shard`.

## Things to do:

- [ ] Check the number of `decData` updates to find out the safe stage while fetching the safe info

### PR DESCRIPTION
**Pull request by yathishram**
## Description:

This PR allows for multiple guardians to simultaneously update the safe stage and recover the safe.

## Added:

List the added features
* `updateDecShard` - To update the shards on the guardian's user profiles
*  `getDecShards` - To fetch the `decShards` for a safe

## Modified:

List the modified features
* Adds a `decShard` key to `SafeMeta` in the `User` field to allow for concurrent writes to DB
* Adds `guardian` field to user data. 

## Todo:

List the TODO features
- [x] Add `Guardian` boolean value on user profiles

### CODE REVIEW

File: src/utils/ceramicBootstrap.js [hunk 1]
```diff
@@ -57,7 +58,7 @@ async function run() {
   const seed = new Uint8Array(randomBytes(32))
   console.log("Created seed", seed)
   // Connect to the local Ceramic node
-  const ceramic = new Ceramic(CERAMIC_URL_TESTNET)
+  const ceramic = new Ceramic(CERAMIC_URL)
```
Comment (koshikraj) [inline src/utils/ceramicBootstrap.js:59]: We need to add the Ceramic URL in `network.json` and use based on the selected network.
test: `https://ceramic-clay.safient.io`
mainnet: `https://ceramic.safient.io`
local and dev: test: `http://0.0.0.0:7007`

**Review by koshikraj — CHANGES_REQUESTED** [review]

**Comment by yathishram** [comment]
> Do we have to manually update this every time we deploy locally?

It's a one-time thing. Like contract addresses. So I guess it's fine for now.

**Review by koshikraj — APPROVED** [review]
